# Configurazione container per i benchmark su singola istanza

services:
  neo4j:
    image: neo4j:5.20.0-community
    container_name: neo4j-benchmark
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      # Imposta limiti memoria Neo4j
      - NEO4J_server_memory_heap_initial__size=4G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2500m
    volumes:
      - ./data/neo4j-sf${SCALE_FACTOR:-0.1}:/data
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G


  postgres:
    image: postgres:14.4
    container_name: postgres-benchmark
    ports:
      - "5432:5432"
    # Imposta limiti memoria PostgreSQL
    command: ["postgres", "-c", "shared_buffers=1536MB", "-c", "work_mem=32MB", "-c", "effective_cache_size=4GB"]
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ldbcsnb
    volumes:
      - ./data/postgres-sf${SCALE_FACTOR:-0.1}:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 5500m
